# Theming
font: JetBrainsMono Nerd Font 12
background: "#282828d0"
color: "#eeeeee"
border: "#332d41"
separator: " âžœ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 1 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: top # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 10

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "p"
    desc: Power
    submenu:
      - key: "s"
        desc: Sleep
        cmd: systemctl suspend & hyprlock
      - key: "r"
        desc: Reboot
        cmd: reboot
      - key: "p"
        desc: Shut down
        cmd: poweroff
  - key: "r"
    desc: Resize
    submenu:
      - key: "h"
        desc: Shrink width
        cmd: niri msg action set-column-width "-10%"
        keep_open: true
      - key: "l"
        desc: Expand width
        cmd: niri msg action set-column-width "+10%"
        keep_open: true
      - key: "j"
        desc: Shrink height
        cmd: niri msg action set-window-height "-10%"
        keep_open: true
      - key: "k"
        desc: Expand height
        cmd: niri msg action set-window-height "+10%"
        keep_open: true
